CREATE TABLE USERS(
	ID INTEGER PRIMARY KEY,
	NAME TEXT NOT NULL,
	TIMEZONE TEXT,
	CREATED_AT TEXT
);

INSERT INTO USERS (NAME, TIMEZONE) VALUES ("JOHN", "PDT");

INSERT INTO USERS (NAME, TIMEZONE) VALUES ("JENNY", "EDT");

INSERT INTO USERS (NAME, TIMEZONE) VALUES ("JANE", "EDT");

SELECT * FROM USERS;

SELECT * FROM USERS WHERE TIMEZONE = "EDT"; -- SELECIONANDO TIMEZONE EDT

SELECT * FROM USERS WHERE TIMEZONE = "PDT"; -- SELECIONANDO TIMEZONE PDT

SELECT COUNT(*) FROM USERS WHERE TIMEZONE = "EDT"; -- QUANTIDADE DE TIMEZONE PELA EDT
